### ISSUE TITLE
[P2PNet] KeyError: 'HungarianAssignerV2 is not in the bbox_assigner registry'

### ISSUE THREAD

**Issue by yaoqi-zd** [ucas-vg/PointTinyBenchmark#57]
Hi, when I train P2PNet on SeaPerson with the command 
```
export GPU=4 && LR=1e-4 && B=2 && WH=(640 640) && CONFIG="TinyPersonV2/p2p/p2p_r50_fpns4_1x_fl_sl1_TinyPersonV2_640" && \
CUDA_VISIBLE_DEVICES=0,1,2,3 PORT=10000 tools/dist_train.sh configs2/${CONFIG}.py $GPU \
--work-dir ../TOV_mmdetection_cache/work_dir/${CONFIG}/trainval${WH[0]}x${WH[1]}_adamlr${LR}_1x_b${B}${GPU}g_coarse/ \
--cfg-options optimizer.lr=${LR} data.samples_per_gpu=${B} \
 data.train.ann_file="data/tiny_set_v2/anns/release/corner/coarse/noise_rg-0-0.25_1/corner_w640_h640/pseuw16h16/rgb_train_w640h640ow100oh100_coarse.json" \
 data.val.ann_file="data/tiny_set_v2/anns/release/rgb_test.json"
```
I get error as below
```
Traceback (most recent call last):
  File "/home/yq223369/.local/lib/python3.7/site-packages/mmcv/utils/registry.py", line 51, in build_from_cfg
    return obj_cls(**args)
  File "/disk2/yaoqi/workspace/Det/PointTinyBenchmark/TOV_mmdetection/mmdet/models/dense_heads/p2p_head.py", line 74, in __init__
    self.assigner = build_assigner(self.train_cfg.assigner)
  File "/disk2/yaoqi/workspace/Det/PointTinyBenchmark/TOV_mmdetection/mmdet/core/bbox/builder.py", line 10, in build_assigner
    return build_from_cfg(cfg, BBOX_ASSIGNERS, default_args)
  File "/home/yq223369/.local/lib/python3.7/site-packages/mmcv/utils/registry.py", line 44, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'HungarianAssignerV2 is not in the bbox_assigner registry'
```
I've searched the keyword 'HungarianAssignerV2' in the whole repo, but find no implementation. would you mind to update the code?

**Comment by yaoqi-zd** [comment]
it seems that some codes related to the 'HungarianV2' is missing, including the 'HungarianV2' class, some cost functions like 'DisCostV2', looking forward for your updates

**Comment by yinglang** [comment]
Ok, I will check it immediately.

**Comment by yinglang** [comment]
I have updated the code. as show in [1](https://github.com/ucas-vg/PointTinyBenchmark/commit/bda0413a7a4584c343d30a959932272630f2f574) and [2](https://github.com/ucas-vg/PointTinyBenchmark/commit/30ba0c8bdb0ae4419c60b7ff3a28989c6c748145)

**Comment by yaoqi-zd** [comment]
@yinglang Thanks for your reply, may I ask if the [model config](https://github.com/ucas-vg/PointTinyBenchmark/blob/master/TOV_mmdetection/configs2/TinyPersonV2/p2p/p2p_r50_fpns4_1x_fl_sl1_TinyPersonV2_640.py) contains the final parameters to reproduce performance results in your paper? e.g.
1) network: R50 backbone, FPN neck with output stride=4, P2P head with 4 stacked conv;
2) v2 of hungarian, with focal loss cost and disconstv2;

since I've seen some experimental settings commented in this config, and not sure you have release the final config file
