### ISSUE TITLE
Could you please provide the evaluation code of CPR?

### ISSUE THREAD

**Issue by dk-liang** [ucas-vg/PointTinyBenchmark#64]
I would like to test the point-box-level MAP. However, I can not find the evaluation code.

**Comment by yinglang** [comment]
Hi ,the evaluation code have been put in https://github.com/yinglang/huicv/blob/main/evaluation/location_evaluation.py.
And as to install it , you may need to clone huicv into your TOV_mmdetection directory as 
[install](https://github.com/ucas-vg/PointTinyBenchmark/blob/master/TOV_mmdetection/README.md#download-and-project-setting) told.

**Comment by cxq1** [comment]
Hi, I'm curious how to generate exp/latest_result.json

**Comment by yinglang** [comment]
The generate code can refer to [cocofmt.py](https://github.com/ucas-vg/PointTinyBenchmark/blob/master/TOV_mmdetection/mmdet/datasets/cocofmt.py#L321).
It will run in evaluate step during the training stage.
