### ISSUE TITLE
Visdrone-Person dataset

### ISSUE THREAD

**Issue by GuangqianGuo** [ucas-vg/PointTinyBenchmark#67]
Hi authors:
Noticed that you used visdrone-person dataset in your paper, how can I get it please.
Looking forward to your reply.
Thanks!

**Comment by yinglang** [comment]
Hi, for this project, we do not use Visdrone-person. If you want to obtain the dataset, you can refer to [VisDrone2019 object detection track](https://github.com/VisDrone/VisDrone-Dataset#task-1-object-detection-in-images), the only change to it is delete all annotations that are not person category.
