### ISSUE TITLE
[CPR] evaluate coco

### ISSUE THREAD

**Issue by cxq1** [ucas-vg/PointTinyBenchmark#70]
Hello I am wondering how to evaluate "coarse_point_refine_R50_FPN_1x_COCO400"

**Comment by yinglang** [comment]
As [the readme file](https://github.com/ucas-vg/PointTinyBenchmark/tree/master/TOV_mmdetection/docs/cpr#1-train-on-coco) given, we use the annotation, which estimate from the result of "coarse_point_refine_R50_FPN_1x_COCO400", to train a P2PNet. The evaluation result of P2PNet is the final result.
